camera_matrix:
  cols: 3
  data:
  - 734.1164263012053
  - 0.0
  - 343.79505481303323
  - 0.0
  - 742.2853530230016
  - 229.52917016790624
  - 0.0
  - 0.0
  - 1.0
  rows: 3
camera_name: nuroum_1080p
distortion_coefficients:
  cols: 1
  data:
  - 0.11440076399233819
  - -0.1329055550849643
  - -0.0034176651765074548
  - 0.010826168494386109
  - -5.275057506601566
  rows: 1
image_height: 480
image_width: 640
num_images: 28
reprojection_error: 0.1524194922250111
